/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import proyecto_transversal.AccesoDatos.AlumnoData;
import proyecto_transversal.AccesoDatos.InscripcionData;
import proyecto_transversal.Entidades.Alumno;
import proyecto_transversal.Entidades.Inscripcion;
import proyecto_transversal.Entidades.Materia;

/**
 *
 * @author pablo
 */
public class Formulario_de_inscripcion extends javax.swing.JInternalFrame {
    
    DefaultTableModel tModel = new DefaultTableModel();

    /**
     * Creates new form Formulario_de_inscripcion
     */
    public Formulario_de_inscripcion() {
        initComponents();
        modeloTabla();
        cargarCombo();
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void cargarCombo(){
        AlumnoData aData = new AlumnoData();
        List<Alumno> alumnos = aData.listarAlumnos();
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for(Alumno alumno:alumnos){
            modelo.addElement(alumno.getDni()+","+alumno.getApellido()+","+alumno.getNombre());
        }
        jcAlumnos.setModel(modelo);
    }
    
    
    public void modeloTabla(){
        tModel.addColumn("ID");
        tModel.addColumn("Nombre");
        tModel.addColumn("Año");
        jtMaterias.setModel(tModel);
    }
    
    public void borrarFilas(){
        int f=jtMaterias.getRowCount()-1;
        for(int i=f;i>=0;i--){
            tModel.removeRow(i);
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jcAlumnos = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jrMateriasI = new javax.swing.JRadioButton();
        jrMateriasNoI = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtMaterias = new javax.swing.JTable();
        jbInscribir = new javax.swing.JButton();
        jbAnularInscripcion = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Selecciona el alumno");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Listado de materias");

        buttonGroup1.add(jrMateriasI);
        jrMateriasI.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrMateriasI.setText("Materias inscriptas");
        jrMateriasI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrMateriasIActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrMateriasNoI);
        jrMateriasNoI.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrMateriasNoI.setText("Materias no inscriptas");
        jrMateriasNoI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrMateriasNoIActionPerformed(evt);
            }
        });

        jtMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtMaterias);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1)
                        .addGap(61, 61, 61)
                        .addComponent(jcAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jrMateriasI)
                                .addGap(225, 225, 225)
                                .addComponent(jrMateriasNoI)))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrMateriasI)
                    .addComponent(jrMateriasNoI))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbInscribir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbInscribir.setText("Inscribir");
        jbInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInscribirActionPerformed(evt);
            }
        });

        jbAnularInscripcion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbAnularInscripcion.setText("Anular inscripcion");
        jbAnularInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAnularInscripcionActionPerformed(evt);
            }
        });

        jbSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jbInscribir)
                .addGap(73, 73, 73)
                .addComponent(jbAnularInscripcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbSalir)
                .addGap(64, 64, 64))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbInscribir)
                    .addComponent(jbAnularInscripcion)
                    .addComponent(jbSalir))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInscribirActionPerformed
        // TODO add your handling code here:
        AlumnoData aData = new AlumnoData();
        String dni = jcAlumnos.getSelectedItem().toString();
        Alumno alumno = aData.buscarPorDni(Integer.parseInt(dni.split(",")[0]));
        //Crea una materia en base a una materia seleccionada en la tabla
        Materia materia = new Materia();
        int seleccionado = jtMaterias.getSelectedRow();
        materia.setAnioMateria(Integer.parseInt(tModel.getValueAt(seleccionado, 2).toString()));
        materia.setIdMateria(Integer.parseInt(tModel.getValueAt(seleccionado, 0).toString()));
        materia.setNombre(tModel.getValueAt(seleccionado, 1).toString());
        //Crea una inscripcion nueva
        if(jrMateriasI.isSelected()){
            InscripcionData iData = new InscripcionData();
            Inscripcion inscripcion = new Inscripcion();
            inscripcion.setAlumno(alumno);
            inscripcion.setMateria(materia);
            inscripcion.setNota(0);
            iData.guardarInscripcion(inscripcion);
        }else{
            JOptionPane.showMessageDialog(null,"Debe situarse en la tabla de materias no inscriptas");
        }
    }//GEN-LAST:event_jbInscribirActionPerformed

    private void jbAnularInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAnularInscripcionActionPerformed
        // TODO add your handling code here:
        AlumnoData aData = new AlumnoData();
        String dni = jcAlumnos.getSelectedItem().toString();
        Alumno alumno = aData.buscarPorDni(Integer.parseInt(dni.split(",")[0]));
        //
        int seleccionado = jtMaterias.getSelectedRow();
        InscripcionData iData = new InscripcionData();
        iData.borrarInscripcionPorAlumno(alumno.getIdAlumno(), Integer.parseInt(tModel.getValueAt(seleccionado, 0).toString()));
    }//GEN-LAST:event_jbAnularInscripcionActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jrMateriasNoIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrMateriasNoIActionPerformed
        // TODO add your handling code here:
        borrarFilas();
        AlumnoData aData = new AlumnoData();
        String dni = jcAlumnos.getSelectedItem().toString();
        Alumno alumno = aData.buscarPorDni(Integer.parseInt(dni.split(",")[0]));
        InscripcionData iData = new InscripcionData();
        if(jrMateriasNoI.isSelected()){
            jrMateriasI.setSelected(false);
            List<Materia> materias = iData.obtenerMateriasNoCursadasV2(alumno.getIdAlumno());
            for(Materia lista: materias){
                tModel.addRow(new Object[] {lista.getIdMateria()
                    ,lista.getNombre()
                    ,lista.getAnioMateria()});
            }
        }
    }//GEN-LAST:event_jrMateriasNoIActionPerformed

    private void jrMateriasIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrMateriasIActionPerformed
        // TODO add your handling code here:
        borrarFilas();
        AlumnoData aData = new AlumnoData();
        String dni = jcAlumnos.getSelectedItem().toString();
        Alumno alumno = aData.buscarPorDni(Integer.parseInt(dni.split(",")[0]));
        InscripcionData iData = new InscripcionData();
        if(jrMateriasI.isSelected()){
            jrMateriasNoI.setSelected(false);
            List<Materia> materias = iData.obtenerMateriasCursadasV2(alumno.getIdAlumno());
            for(Materia lista: materias){
            tModel.addRow(new Object[] {lista.getIdMateria()
                    ,lista.getNombre()
                    ,lista.getAnioMateria()});
            }
        }
    }//GEN-LAST:event_jrMateriasIActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAnularInscripcion;
    private javax.swing.JButton jbInscribir;
    private javax.swing.JButton jbSalir;
    private javax.swing.JComboBox<String> jcAlumnos;
    private javax.swing.JRadioButton jrMateriasI;
    private javax.swing.JRadioButton jrMateriasNoI;
    private javax.swing.JTable jtMaterias;
    // End of variables declaration//GEN-END:variables
}
